### ISSUE TITLE
About the title name : Functional Reactive Programming

### ISSUE THREAD

**Issue by dakeshi** [crowdsourcebooks/theswiftbook#10]
FRP is an ambiguous and restricted expression as [this discussion](https://github.com/ReactiveX/RxSwift/pull/94) about definition FRP and RxSwift. - it's amazing discussion.!!

So, I suggest `Functional, Reactive Programming` for this section title.

**What is different?**

In above discussion, they agree that FRP is not equal to RxSwift(or Reactive Extensions) but FRP become the general term to represent Rx libraries and concepts. 

So, to make clear description, `Functional, Reactive Programming` would be better choice for the title name.

**Comment by vandadnp** [comment]
Thanks for this initiative. I was thinking that the FRP chapter could talk about the basics of FRP but not go into details about RxSwift as such, since this book is about Swift, and not about RxSwift. Could we keep the chapter title the same and avoid going into details about RxSwift?

**Comment by dakeshi** [comment]
> I was thinking that the FRP chapter could talk about the basics of FRP 

Actually, it is `Functional or Reactive Programming`,not FRP, although we do not dealt with RxSwift.
 [The original `FRP` definition is very restricted.](https://begriffs.com/posts/2015-07-22-essence-of-frp.html?hn=2) Even though it is a misnomer to call `FRP`, it become a term to represent some logic have functional, reactive features. 

 as time gones by and people use a term misused very To be called `FRP` about some logic, it need  has very  



So, It would be better to change title to `Functional, Reactive Programming` or `Functional Programming`.
The most of tutorials, speaking about FRP is not satisfied the real FRP requirements, 
 Even though it is not fulfilled with the real FRP requirements,

**Comment by vandadnp** [comment]
Fixed in https://github.com/crowdsourcebooks/theswiftbook/commit/2e716f8b773a1e623102fc9bcc5d7c51356734e5

Let me know if this fixes the issue. Thanks 👍

**Comment by dakeshi** [comment]
Perferct. 💯  Thanks too. 😄
