### ISSUE TITLE
Inaccurate claim that structs are immutable

### ISSUE THREAD

**Issue by timvermeulen** [crowdsourcebooks/theswiftbook#16]
> `String` data type is a `struct` in Swift, therefore it is immutable.

This doesn't really make sense. Immutability simply depends on the use of `let` vs `var` and that has nothing to do with the `String` type. `String` even has mutating methods such as `append(_:)` and `insert(_:atIndex:)`.

**Comment by dakeshi** [comment]
I think it should be `value type` instead of `immutable`. I'll check more about String type.
Thank you @timvermeulen

**Comment by vandadnp** [comment]
Fixed here https://github.com/crowdsourcebooks/theswiftbook/commit/20c31bc25d952922546ffabcdfc8488e751d58f4

Thanks for the feedback
