### ISSUE TITLE
Int cannot be either signed or unsigned

### ISSUE THREAD

**Issue by timvermeulen** [crowdsourcebooks/theswiftbook#17]
The explanation of the `Int` type is

>An integer, that can be either signed or unsigned, meaning that it can either be positive or negative.

`Int` is either `Int32` or `Int64` depending on the processor you're using, and both of these types are signed. Of course there are other types for unsigned integers, but these do not belong to `Int` in any way.

Also, this sentence is very ambiguous. It seems to suggest that signed integers are positive and unsigned integers are negative.

**Comment by dakeshi** [comment]
You're right. @timvermeulen . It's an unclear definition. 
We need to update it. Thank you. 👍

**Comment by vandadnp** [comment]
This was fixed by @dakeshi in https://github.com/crowdsourcebooks/theswiftbook/pull/18

Thank you for the feedback 👍
