### ISSUE TITLE
How was adding type inference in chapter 1?

### ISSUE THREAD

**Issue by dakeshi** [crowdsourcebooks/theswiftbook#19]
I think that we need to talk about `type inference` in chapter 1.
We use `type inference` concept in DataTypes, Variables section as well as Contants section.

So, I suggest that place it in the beginning part of Data types and then we can use a reference in other files such as String, Integers, Constants or Variable.

**Comment by vandadnp** [comment]
Fixed in https://github.com/crowdsourcebooks/theswiftbook/commit/391e3a31affefb9bbea0e1ff11ba4c8f1c511695

If you are happy with the text, please let me know and I can close the issue.

**Comment by dakeshi** [comment]
Nice. 👍  I'll update the type reference link used in integers.md.

**Comment by vandadnp** [comment]
Very nice 🌷
