### ISSUE TITLE
About Optionals.md

### ISSUE THREAD

**Issue by dakeshi** [crowdsourcebooks/theswiftbook#20]
Hello. @vandadnp 

I'm going to write about Optionals.md and have some questions about sections to make clear before I start it.

- safely unwrapping
Do you means an optional binding or if statement with nil? 

- switching
what does that means? an optional binding?

**Comment by dakeshi** [comment]
refer to c136c81e501e2fd4d15aee3bf648159546913b48

**Comment by vandadnp** [comment]
Hi,

I've started going through all the chapters and leaving notes for contributors on what every section needs to explain to the reader. Is that alright?

/v
