### ISSUE TITLE
Multi-languages support

### ISSUE THREAD

**Issue by dakeshi** [crowdsourcebooks/theswiftbook#4]
As gitbook.com documents and pro-git examples, gitbook support multi-languages.
I can not sure it is good idea for this kind of project because it is difficult to keep up-to-dated version in each languages version and process a lot of PRs. But it is worth to considering it.

I can manage korean version.
So, how was get started in small two, English and Korean?

**Comment by vandadnp** [comment]
This is a great idea. I think the community would really appreciate a crowd sourced multilingual book about Swift. We need to then think about the project structure and think about how we can keep everything up to date in every language... perhaps we could make official releases of the English version of the book, and then translate that version as it is to Korean and other languages. But to keep everything up to date all the time might be impossible.

**Comment by vandadnp** [comment]
continue discussion here: https://github.com/crowdsourcebooks/theswiftbook/issues/7
